openapi: 3.0.0
info:
  title: User API
  version: 1.0.0
  description: API for retrieving the currently authenticated user

paths:
  /user/current:
    get:
      summary: Get current user
      description: Retrieves the details of the currently authenticated user
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          description: Unauthorized
        "404":
          description: User not found

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        email:
          type: string
          format: email
        created_at:
          type: string
          format: date-time
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
