openapi: 3.0.0
info:
  title: Image Upload API
  version: 1.0.0
  description: A simple API for uploading JPEG images
servers:
  - url: http://localhost:6767/v1/upload
paths:
  /upload:
    post:
      summary: Upload a JPEG image
      description: Endpoint to upload a JPEG image file
      operationId: uploadImage
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                id:
                  type: string
                image:
                  type: string
                  format: binary
      responses:
        "200":
          description: Successful upload
          content:
            application/json: {}
components:
  schemas: {}
